#!/usr/bin/env python3
"""Render a project's Homebrew formula the way homebrew-releaser will, and lint it.

The formulae in a tap are generated: homebrew-releaser (run directly as a
GitHub Action, or via `tapper push`) splices three project-owned fragments
into a fixed skeleton --

    formula_includes   the extra DSL (depends_on / service / caveats), which
                       the generator injects ABOVE desc
    install            the body of `def install`
    test               the body of `test do`

-- and fills the rest from the GitHub repo (description, licence, release
assets). Nothing validates those fragments before a release, so a style
offence or a hardcoded personal PATH only becomes visible once it is already
committed to the tap, where it cannot be fixed: the file carries a DO NOT EDIT
banner and the next release overwrites it.

This renders the formula from the fragments and runs `ruby -c` + `brew style`
on the result, so the offence surfaces at release time instead.

Usage:
    check-formula.py <project-dir> [--name NAME] [--verbose]
    check-formula.py <project-dir> --emit          # print the render, lint nothing

Reads tapper.yaml when present, otherwise the homebrew-releaser step in
.github/workflows/release.yml.

Exit status:
    0  no project-owned offence
    1  at least one project-owned offence
    2  could not find or parse the project's formula inputs
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# brew style loads the whole live tap, so a synthetic formula whose class name
# collides with an installed one reports bogus Lint/DuplicateMethods. Render
# under a name nothing will ever ship.
CLASS_SUFFIX = "Renderchecksynthetic"

# Placeholders. Only their shape matters: a 64-char hex sha256 and a plain
# semver keep the DSL well formed without pretending to describe a real asset.
PLACEHOLDER_SHA = "0" * 64
PLACEHOLDER_VERSION = "0.0.0"
PLACEHOLDER_LICENSE = "Apache-2.0"

# homebrew-releaser injects formula_includes above desc, so every formula that
# uses includes trips ComponentsOrder. It is not fixable from the project: the
# fix belongs upstream in Justintime50/homebrew-releaser. Report it, do not
# fail on it.
GENERATOR_OWNED = re.compile(
    r"FormulaAudit/ComponentsOrder: desc \(line \d+\) should be put before"
)

# ENT-005: brew services get a spartan PATH, and formulae compensate by baking
# the author's own toolchain layout into the plist. That is wrong on any other
# prefix, and it puts user-writable directories ahead of /usr/bin for a daemon.
# Homebrew already names the right value: std_service_path_env expands to
# "#{HOMEBREW_PREFIX}/bin:#{HOMEBREW_PREFIX}/sbin:/usr/bin:/bin:/usr/sbin:/sbin".
STD_PATH = "std_service_path_env"

PATH_POLICY = [
    ("/opt/homebrew", f"hardcoded prefix, wrong on Intel and Linuxbrew; use {STD_PATH}"),
    ("/usr/local/bin", f"hardcoded prefix; use {STD_PATH}"),
    ('ENV["HOME"]', "the installing user's home, baked in at load time; use Dir.home"),
    ("/.cargo/bin", "user-writable dir ahead of /usr/bin; declare a depends_on"),
    ("/.py/bin", "personal venv; declare a depends_on instead"),
    ("/.claude/local", "personal tool dir; declare a depends_on instead"),
]

# homebrew-releaser truncates the repo description to Homebrew's field limit.
DESC_LIMIT = 80

# brew style rejects these in a desc, and a desc comes from the repo, so the
# fix is `gh repo edit --description`, not a formula edit.
DESC_SUBSTITUTIONS = [("command line", "command-line")]

SKELETON = """\
# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class {klass} < Formula
{includes}\
  desc "{desc}"
  homepage "https://github.com/{repo}"
  url "https://github.com/{repo}/archive/refs/tags/v{version}.tar.gz"
  version "{version}"
  sha256 "{sha}"
  license "{license}"

{bottles}
  def install
{install}
  end

  test do
{test}
  end
end
"""

BOTTLE_BLOCK = """\
  on_{os} do
    on_{arch} do
      url "https://github.com/{repo}/releases/download/v{version}/{name}-{version}-{os_tag}-{arch_tag}.tar.gz"
      sha256 "{sha}"
    end
  end
"""


def indent(text, spaces):
    """homebrew-releaser indents each fragment line uniformly; blank lines stay blank."""
    pad = " " * spaces
    out = []
    for line in text.rstrip("\n").split("\n"):
        out.append(pad + line if line.strip() else "")
    return "\n".join(out)


def load_inputs(project):
    """Return (name, repo, includes, install, test) from tapper.yaml or release.yml."""
    tapper_yaml = project / "tapper.yaml"
    if tapper_yaml.is_file():
        return load_from_tapper(project, tapper_yaml)
    workflow = project / ".github" / "workflows" / "release.yml"
    if workflow.is_file():
        return load_from_workflow(project, workflow)
    raise SystemExit(f"{project}: no tapper.yaml and no .github/workflows/release.yml")


def read_yaml(path):
    try:
        import yaml
    except ImportError:
        raise SystemExit("PyYAML is required: uv pip install pyyaml")
    with path.open() as fh:
        return yaml.safe_load(fh)


def load_from_tapper(project, path):
    cfg = read_yaml(path) or {}
    repo = cfg.get("repo") or ""
    if not repo:
        raise SystemExit(f"{path}: no `repo`")

    def fragment(key):
        rel = cfg.get(key)
        if not rel:
            return ""
        f = project / rel
        if not f.is_file():
            raise SystemExit(f"{path}: {key} points at missing {rel}")
        return f.read_text()

    return (
        repo.split("/")[-1],
        repo,
        fragment("formula_includes_file"),
        fragment("install_file") or cfg.get("install", "") or "",
        cfg.get("test", "") or "",
    )


def repo_from_git(project):
    """owner/name from the git remote. The directory name is not reliable: a
    worktree is usually called <repo>-<branch-slug>, and the formula would then
    be rendered under that name."""
    proc = subprocess.run(
        ["git", "-C", str(project), "remote", "get-url", "origin"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return ""
    url = proc.stdout.strip().removesuffix(".git")
    parts = url.replace(":", "/").split("/")
    return "/".join(parts[-2:]) if len(parts) >= 2 else ""


def load_from_workflow(project, path):
    """Pull the `with:` block of the Justintime50/homebrew-releaser step."""
    doc = read_yaml(path) or {}
    for job in (doc.get("jobs") or {}).values():
        for step in job.get("steps") or []:
            uses = str(step.get("uses", ""))
            if "homebrew-releaser" not in uses:
                continue
            with_ = step.get("with") or {}
            repo = repo_from_git(project) or doc.get("env", {}).get(
                "GITHUB_REPOSITORY", ""
            )
            if not repo:
                raise SystemExit(f"{project}: cannot determine owner/repo")
            name = repo.split("/")[-1]
            return (
                name,
                repo,
                with_.get("formula_includes", "") or "",
                with_.get("install", "") or "",
                with_.get("test", "") or "",
            )
    raise SystemExit(f"{path}: no homebrew-releaser step")


def render(name, repo, includes, install, test, klass=None, meta=None):
    meta = meta or {}
    version = meta.get("version", PLACEHOLDER_VERSION)
    sha = meta.get("sha", PLACEHOLDER_SHA)
    bottles = meta.get("bottles")
    if bottles is None:
        bottles = BOTTLE_BLOCK.format(
            os="macos", arch="arm", os_tag="darwin", arch_tag="arm64",
            repo=repo, version=version, name=name, sha=sha,
        )
    bottles = bottles.rstrip("\n") + "\n"
    inc = indent(includes, 2) + "\n\n" if includes.strip() else ""
    return SKELETON.format(
        klass=klass or (name.replace("-", " ").title().replace(" ", "") + CLASS_SUFFIX),
        includes=inc,
        desc=meta.get("desc", "Placeholder description for the render check"),
        repo=repo,
        version=version,
        sha=sha,
        license=meta.get("license", PLACEHOLDER_LICENSE),
        bottles=bottles,
        install=indent(install, 4),
        test=indent(test, 4),
    )


def meta_from_formula(path):
    """Lift the generator-filled fields out of a formula the generator wrote.

    Rendering with these turns --emit into an equality test: the output must
    match the shipped file byte for byte, which is what proves this script
    still models homebrew-releaser correctly."""
    text = Path(path).read_text()
    def one(pattern):
        m = re.search(pattern, text, re.M)
        if not m:
            raise SystemExit(f"{path}: no match for {pattern}")
        return m.group(1)
    return {
        "class": one(r"^class (\w+) < Formula"),
        "desc": one(r'^  desc "([^"]+)"'),
        "version": one(r'^  version "([^"]+)"'),
        "sha": one(r'^  sha256 "([^"]+)"'),
        "license": one(r'^  license "([^"]+)"'),
        "bottles": text[text.index("  on_macos do"):text.index("  def install")],
    }


def lint_repo_metadata(repo):
    """desc and license are not in any project file: homebrew-releaser reads
    them from the GitHub repo. A missing LICENSE or an awkward description only
    shows up as a formula offence after the release, so check them here."""
    proc = subprocess.run(
        ["gh", "api", f"repos/{repo}", "--jq",
         "{description: .description, license: .license.spdx_id}"],
        capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return [f"could not read repo metadata: {proc.stderr.strip().splitlines()[-1:]}"]
    meta = json.loads(proc.stdout)
    problems = []
    desc = meta.get("description")
    if not desc:
        problems.append("repo has no description; homebrew-releaser crashes on null")
    else:
        if len(desc) > DESC_LIMIT:
            problems.append(
                f"description is {len(desc)} chars; homebrew-releaser truncates at "
                f"~{DESC_LIMIT} and will cut mid-word"
            )
        for bad, good in DESC_SUBSTITUTIONS:
            if bad in desc.lower():
                problems.append(f'description says "{bad}"; brew style wants "{good}"')
    if not meta.get("license"):
        problems.append(
            "repo has no detected licence, so the formula will omit `license`; "
            "add a root LICENSE and it appears on the NEXT release, not this one"
        )
    return problems


def lint_path_policy(includes):
    hits = []
    for lineno, line in enumerate(includes.split("\n"), 1):
        for needle, why in PATH_POLICY:
            if needle in line:
                hits.append((lineno, needle, why))
    return hits


def brew_style(path):
    """Return (project_owned, generator_owned) offence lines."""
    if not shutil.which("brew"):
        raise SystemExit("brew not found")
    proc = subprocess.run(
        ["brew", "style", str(path)], capture_output=True, text=True
    )
    mine, theirs = [], []
    for line in (proc.stdout + proc.stderr).split("\n"):
        if not re.search(r":\d+:\d+: [CWEF]: ", line):
            continue
        (theirs if GENERATOR_OWNED.search(line) else mine).append(line.strip())
    return mine, theirs


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("project", type=Path)
    ap.add_argument("--emit", action="store_true", help="print the render and exit")
    ap.add_argument("--meta", type=Path,
                    help="JSON of real desc/version/sha/license/bottles/class")
    ap.add_argument("--from-formula", type=Path, metavar="TAP_FORMULA",
                    help="take desc/version/sha/licence/bottles from an already "
                         "generated formula, so --emit reproduces it exactly")
    ap.add_argument("--online", action="store_true",
                    help="also check the GitHub repo's description and licence")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    project = args.project.resolve()
    name, repo, includes, install, test = load_inputs(project)
    meta = json.loads(args.meta.read_text()) if args.meta else {}
    if args.from_formula:
        meta = meta_from_formula(args.from_formula)
    text = render(name, repo, includes, install, test,
                  klass=meta.pop("class", None), meta=meta)

    if args.emit:
        sys.stdout.write(text)
        return 0

    failures = 0
    with tempfile.TemporaryDirectory() as tmp:
        # brew style only applies the Homebrew formula cops (and skips the
        # Sorbet/FetchEnvVar cops meant for Homebrew's own Ruby) when the file
        # sits in a directory named Formula. Lint it anywhere else and you get
        # offences the real tap never reports.
        formula_dir = Path(tmp) / "Formula"
        formula_dir.mkdir()
        formula = formula_dir / f"{name}.rb"
        formula.write_text(text)

        syntax = subprocess.run(
            ["ruby", "-c", str(formula)], capture_output=True, text=True
        )
        if syntax.returncode != 0:
            print(f"FAIL  {name}: rendered formula does not parse")
            print(syntax.stderr.strip())
            return 1
        print(f"ok    {name}: rendered formula parses")

        mine, theirs = brew_style(formula)

    if args.online:
        for problem in lint_repo_metadata(repo):
            print(f"FAIL  {name}: {problem}")
            failures += 1

    for hit in lint_path_policy(includes):
        lineno, needle, why = hit
        print(f"FAIL  {name}: formula_includes line {lineno}: {needle} -- {why}")
        failures += 1

    for line in mine:
        print(f"FAIL  {name}: {line.split(': ', 1)[-1] if args.verbose else line}")
        failures += 1

    for line in theirs:
        print(f"note  {name}: generator-owned, not fixable here: {line}")

    if failures:
        print(f"\n{name}: {failures} project-owned offence(s)")
        return 1
    print(f"\n{name}: clean ({len(theirs)} generator-owned note(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
